In [16]:
import os
import pandas as pd
import pickle as pkl
import numpy as np

# For 10 fold CV
# col = ["Task", "Metrics", "Rhythm", "Fold-1", "Fold-2", "Fold-3", "Fold-4", "Fold-5", "Fold-6", "Fold-7", "Fold-8", "Fold-9", "Fold-10", "Average", "Std"]

# For 8 fold CV
col = ["Task", "Metrics", "Rhythm", "Fold-1", "Fold-2", "Fold-3", "Fold-4", "Fold-5", "Fold-6", "Fold-7", "Fold-8", "Average", "Std"]

# save_file = './results_k-foldCV_unseen_trials.csv'
save_file = './results_10-foldCV_unseen_subjects.csv'
# read_path = '/DEAP_k-foldCV_unseen_trials_results'#
read_path = '/DEAP_10-foldCV_unseen_subjects_results'

try:
    df = pd.read_csv(save_file)
except:
    df = pd.DataFrame(columns=col)

emotions = ['arousal', 'dominance', 'valence']
bands = ['delta', 'theta', 'alpha', 'beta', 'gamma', 'all']

for e in emotions:
    for b in bands:
        filename = f'./eeg_data{read_path}/DEAP_{e}_{b}.pkl'
        if os.path.exists(filename):
            with open(filename, 'rb') as f:
                res = pkl.load(f)
            acc = np.array(res['accuracy'])[:,1]
            values = np.concatenate(([e, 'Accuracy', b], acc, [np.average(acc), np.std(acc)]), axis=0)
            new_row = dict(zip(col, values))
            df = df.append(new_row, ignore_index=True)

df.to_csv(save_file, index=False)


In [17]:

df.tail()

Task   Metrics Rhythm               Fold-1               Fold-2  \
0    arousal  Accuracy   beta  0.48750001192092896   0.5062500238418579   
1  dominance  Accuracy   beta   0.5002315044403076   0.5175926089286804   
2    valence  Accuracy   beta   0.5074074268341064  0.49004629254341125   

                Fold-3              Fold-4              Fold-5  \
0  0.49074074625968933   0.510879635810852  0.5009258985519409   
1   0.5094907283782959  0.5046296119689941  0.5164352059364319   
2   0.5074074268341064  0.5136573910713196  0.4895833432674408   

                Fold-6               Fold-7               Fold-8  \
0   0.4962962865829468   0.5076388716697693  0.49004629254341125   
1  0.49328702688217163  0.44212964177131653   0.5083333253860474   
2   0.5018518567085266   0.5131944417953491   0.5069444179534912   

               Average                   Std  
0  0.49878472089767456  0.008363618853068713  
1   0.4990162067115307  0.022767632170587648  
2   0.5037615746259689   0.00877780841123111

In [ ]:
import os
import pandas as pd
import pickle as pkl
import numpy as np

filename = f'./eeg_data{read_path}/DEAP_{e}_{b}.pkl'
if os.path.exists(filename):
    with open(filename, 'rb') as f:
        res = pkl.load(f)
    acc = np.array(res['accuracy'])[:,1]
    values = np.concatenate(([e, 'Accuracy', b], acc, [np.average(acc), np.std(acc)]), axis=0)
    new_row = dict(zip(col, values))
    df = df.append(new_row, ignore_index=True)

In [26]:
import pickle as pkl
import matplotlib.pyplot as plt
import pandas as pd

file = "/home/hyojinju/multi-channel-eeg-deep-cnn-emotion-recognition/src/eeg_data/DEAP_k-foldCV_unseen_trials_results/DEAP_arousal_beta.pkl"
# file = "/home/hyojinju/multi-channel-eeg-deep-cnn-emotion-recognition/src/eeg_data/DEAP_k-foldCV_unseen_trials_results/DEAP_valence_beta.pkl"

with open(file, 'rb') as f:
    res = pkl.load(f)

for i in range(10):
    print(res['accuracy'][i][1])
    print(res['confusion_matrix'][i])
# df = pd.DataFrame(res['confusion_matrix'][i])
# df.tail()

0.5338541865348816
[[ 655  452]
 [1159 1190]]
0.5925925970077515
[[ 350 1081]
 [ 327 1698]]
0.5578703880310059
[[ 836 1054]
 [ 474 1092]]
0.5202546119689941
[[1231 1253]
 [ 405  567]]
0.5656828880310059
[[970 866]
 [635 985]]
0.5960648059844971
[[1471  959]
 [ 437  589]]
0.5856481194496155
[[1656 1044]
 [ 388  368]]
0.5943287014961243
[[1028  430]
 [ 972 1026]]
0.45457175374031067
[[ 824  310]
 [1575  747]]
0.5309606194496155
[[1000  296]
 [1325  835]]


In [27]:
import pickle as pkl
import matplotlib.pyplot as plt
import pandas as pd

file = "/home/hyojinju/multi-channel-eeg-deep-cnn-emotion-recognition/src/eeg_data/DEAP_10-foldCV_unseen_subjects_results/DEAP_arousal_beta.pkl"
# file = "/home/hyojinju/multi-channel-eeg-deep-cnn-emotion-recognition/src/eeg_data/DEAP_10-foldCV_unseen_subjects_results/DEAP_valence_beta.pkl"

with open(file, 'rb') as f:
    res = pkl.load(f)

for i in range(8):
    print(res['accuracy'][i][1])
    print(res['confusion_matrix'][i])
# df = pd.DataFrame(res['confusion_matrix'][i])
# df.tail()

0.5039351582527161
[[1232 1225]
 [ 918  945]]
0.519444465637207
[[1291  653]
 [1423  953]]
0.49166667461395264
[[ 891 1620]
 [ 576 1233]]
0.494907408952713
[[1218 1428]
 [ 754  920]]
0.5277777910232544
[[1468  746]
 [1294  812]]
0.5583333373069763
[[2012  445]
 [1463  400]]
0.510879635810852
[[1059 1020]
 [1093 1148]]
0.5280092358589172
[[1866  537]
 [1502  415]]


In [25]:
import pickle as pkl
import matplotlib.pyplot as plt
import pandas as pd

# file = "/home/hyojinju/multi-channel-eeg-deep-cnn-emotion-recognition/src/eeg_data/DEAP_10-foldCV_unseen_subjects_results/DEAP_arousal_beta.pkl"
file = "/home/hyojinju/multi-channel-eeg-deep-cnn-emotion-recognition/src/eeg_data/DEAP_10-foldCV_results/DEAP_valence_beta.pkl"

with open(file, 'rb') as f:
    res = pkl.load(f)

for i in range(10):
    print(res['accuracy'][i][1])
    print(res['confusion_matrix'][i])
# df = pd.DataFrame(res['confusion_matrix'][i])
# df.tail()

0.9872685074806213
[[1930   13]
 [  31 1482]]
0.9910300970077515
[[1877   25]
 [   6 1548]]
0.9884259104728699
[[1810   34]
 [   6 1606]]
0.9780092835426331
[[1851    6]
 [  70 1529]]
0.9866898059844971
[[1814    8]
 [  38 1596]]
0.9849537014961243
[[1891    5]
 [  47 1513]]
0.9924768805503845
[[1863    9]
 [  17 1567]]
0.9904513955116272
[[1882   11]
 [  22 1541]]
0.9794560074806213
[[1840    0]
 [  71 1545]]
0.9317129850387573
[[1842    0]
 [ 236 1378]]
